export const LOAD_CURRENT_USER = "[COMMON] LOAD_CURRENT_USER";
export const LOADING_CURRENT_USER = "[COMMON] LOADING_CURRENT_USER";
export const LOAD_CURRENT_USER_FULFILLED = "[COMMON] LOAD_CURRENT_USER_FULFILLED";
export const LOAD_CURRENT_USER_REJECTED = "[COMMON] LOAD_CURRENT_USER_REJECTED";